# Numpy 

In [5]:
# NumPy is a Python library.

# NumPy is used for working with arrays.

In [1]:
# Start by installing the numpy library in case it is not already installed !
!pip install numpy

^C


In [3]:
# Creating a Numpy array
import numpy as np
l = [23, 45, 55, 67]
Array=np.array(l)
print(Array)
print(l)
print(type(l))
print(type(Array))

[23 45 55 67]
[23, 45, 55, 67]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# Difference between "List" & "Numpy arrays"

Array=np.array([23, 45, 55, 67])
My_List=[23, 45, 55, 67]
print("Array:",type(Array))
print("My_List:",type(My_List))


Array: <class 'numpy.ndarray'>
My_List: <class 'list'>


In [5]:
# You can pass a list, tuple or any array-like object into the array() method

Array_1=np.array([23, 45, 55, 67])
Array_2=np.array((23, 45, 55, 67))
print(type(Array_1))
print(type(Array_2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
# You can create any array dimension you want

# O-D array
arr_0=np.array(45)
print(arr_0)
print("Dimension of the array is",arr_0.ndim)

print("***********************")

# 1-D array
arr_1=np.array([23, 45, 55, 67])
print(arr_1)
print("Dimension of the array is",arr_1.ndim)
print("***********************")

# 2-D array
arr_2=np.array([[23, 45, 55, 67],[34, 123, -45, 22]])
print(arr_2)
print("Dimension of the array is",arr_2.ndim)
print("***********************")

# 3-D array
arr_3=np.array([[[23, 45, 55, 67],[34, 123, -45, 22]],
                [[34, 123, -45, 22],[10, 78, -33, 9]]])
print(arr_3)
print("Dimension of the array is",arr_3.ndim)
print(arr_3[1,1,2])


45
Dimension of the array is 0
***********************
[23 45 55 67]
Dimension of the array is 1
***********************
[[ 23  45  55  67]
 [ 34 123 -45  22]]
Dimension of the array is 2
***********************
[[[ 23  45  55  67]
  [ 34 123 -45  22]]

 [[ 34 123 -45  22]
  [ 10  78 -33   9]]]
Dimension of the array is 3
-33


In [13]:
# NumPy Array Indexing

arr_1=np.array([23, 45, 55, 67])
print(arr_1[0])
print("***********************")

arr_2=np.array([[23, 45, 55, 67],[34, 123, -45, 22]]) 
print(arr_2[1])
print(arr_2[0,3])
print("***********************")

arr_3=np.array([[23, 45, 55, 67],[34, 123, -45, 22],[10, 78, -33, 9]])
print(arr_3[1])
print(arr_3[0,3])

# Ask them to create a 1-D array using arr_3 

23
***********************
[ 34 123 -45  22]
67
***********************
[ 34 123 -45  22]
67


In [14]:
# Array of arrays

array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array[0, 1, 2])

6


In [17]:
#Checking array shape and reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("the first array:")
print(arr)
print("the shape of the first array is:",arr.shape)


newarr = arr.reshape(4, 3)
print("the second array:")
print(newarr)

print("the shape of the second array is:",newarr.shape)

newarr = newarr.reshape(2, 3, 2)
print("the third array:")
print(newarr)

print("the shape of the third array is:",newarr.shape)


the first array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
the shape of the first array is: (12,)
the second array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
the shape of the second array is: (4, 3)
the third array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
the shape of the third array is: (2, 3, 2)


In [33]:
#Sorting an array

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [19]:
#Operations on Numpy arrays
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print("Addition:",newarr)

newarr = np.subtract(arr1, arr2)
print("Substraction:",newarr)

newarr = np.multiply(arr1, arr2)
print("Multiplication:",newarr)

newarr = np.divide(arr1, arr2)
print("Division:",newarr)

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)
print("Power of:",newarr)

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)
print("Absolute value:",newarr)

Addition: [30 32 34 36 38 40]
Substraction: [-10 -10 -10 -10 -10 -10]
Multiplication: [200 231 264 299 336 375]
Division: [0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
Power of: [      1000    3200000  729000000 -520093696       2500          0]
Absolute value: [1 2 1 2 3 4]


In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

val = np.sum(arr1)
print("Summation:",val)

val = np.sum([arr1, arr2])
print("Summation of two arrays elements:",val)

newarr = np.sum([arr1, arr2], axis=1)

print("Summation over 1 axis",newarr)

Summation: 6
Summation of two arrays elements: 12
Summation over 1 axis [6 6]


In [24]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])
print("Product:",x)

newarr = np.prod([arr1, arr2], axis=1)

print("Product over 1 axis:",newarr)

Product: 40320
Product over 1 axis: [  24 1680]


In [25]:
#Floor and Ceil

arr = np.floor([-3.1666, 3.6667])

print(arr)

arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-4.  3.]
[-3.  4.]


In [26]:
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [27]:
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [28]:
#Trigonometric

#Sin

x = np.sin(np.pi/2)

print("Sin:",x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print("Sin array:",x)

arr = np.array([90, 180, 270, 360])

x = np.cos(np.pi/2)

print("Cos:",x)

x = np.tan(np.pi/2)

print("Tan:",x)

x = np.deg2rad(arr)

print("Degrees:",x)

Sin: 1.0
Sin array: [1.         0.8660254  0.70710678 0.58778525]
Cos: 6.123233995736766e-17
Tan: 1.633123935319537e+16
Degrees: [1.57079633 3.14159265 4.71238898 6.28318531]


In [29]:
#Cross Product
# Use numpy.cross() function
arr = np.array([2, 4])
arr1 = np.array([1, 5])
newarr = np.cross(arr, arr1)
print("Cross Product",newarr)
newarr = np.dot(arr,arr1)
print("Dot Product",newarr)

Cross Product 6
Dot Product 22


In [30]:
#Transpose
arr = np.array([[1, 2],
                [4, 5],
                [7, 8]])
 
# before transpose
print("before transpose:")
print(arr)
 
# after transpose
print("after transpose:")
print(arr.transpose())

before transpose:
[[1 2]
 [4 5]
 [7 8]]
after transpose:
[[1 4 7]
 [2 5 8]]


In [32]:
#Transpose
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
 
# before transpose
print("before transpose:")
print(arr)
 
# after transpose
print("after transpose:")
print(arr.transpose())

before transpose:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
after transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
